// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    SHOPIFY_API_KEY?: string;
    SHOPIFY_API_SECRET?: string;
    SHOPIFY_APP_URL?: string;
    DATABASE_URL?: string;
    DIRECT_URL?: string;
    SCOPES?: string;
    SHOP_CUSTOM_DOMAIN?: string;
}